### ISSUE TITLE
CI Integration

### ISSUE THREAD

**Issue by froehlichA** [froehlichA/pax#26]
While pax can already be automated pretty heavily, I'd like to provide a preset for the github ci so modpack makers don't have to look up how to make them themselves.
Ties in with https://github.com/froehlichA/pax/issues/15

**Comment by MrAwesomeRocks** [comment]
Here's a file you could possibly use (assuming the [OneFlow](https://www.endoflineblog.com/oneflow-a-git-branching-model-and-workflow#variation-develop-master) branching strategy).

```yml
name: Build & Push

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:

env:
  PROJECT_NAME: "CHANGE_ME"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-tag:
    name: Get latest tag
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.version.outputs.tag }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get project version
        id: version
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: "unknown"

  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.changelog.outputs.changelog }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v1.0.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Write changelog to file
        run: echo '${{ steps.changelog.outputs.changelog }}' > changelog.txt

      - name: Store changelog
        uses: actions/upload-artifact@v2
        with:
          name: changelog
          path: changelog.txt

  build:
    name: Build Modpack
    runs-on: ubuntu-latest
    needs: [get-tag, changelog]

    steps:
      - name: Download PAX
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: froehlichA/pax
          file: "pax"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: "modpack"

      - name: Download changelog
        uses: actions/download-artifact@v2
        with:
          name: changelog
          path: modpack

      - name: Create ZIP
        run: |
          sudo chmod +x ./pax
          ./pax export

      - name: Move and rename ZIP
        run: |
          ls -la
          mv .out/${{ env.PROJECT_NAME }}.zip ./${{ env.PROJECT_NAME }}-${{ needs.get-tag.outputs.tag }}.zip

      - name: Upload zip
        uses: actions/upload-artifact@v2
        with:
          name: modpack-zip
          path: ${{ env.PROJECT_NAME }}-${{ needs.get-tag.outputs.tag }}.zip

  release-gh:
    name: Release to Github
    runs-on: ubuntu-latest
    needs: [build, changelog, get-tag]

    steps:
      - name: Download modpack ZIP
        uses: actions/download-artifact@v2
        with:
          name: modpack-zip

      - name: Download changelog
        uses: actions/download-artifact@v2
        with:
          name: changelog

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          body_path: changelog.txt
          files: ${{ env.PROJECT_NAME }}-${{ needs.get-tag.outputs.tag }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-cf:
    name: Release to CurseForge
    runs-on: ubuntu-latest
    needs: [build, changelog, get-tag]

    steps:
      - name: Download modpack ZIP
        uses: actions/download-artifact@v2
        with:
          name: modpack-zip

      - name: Get release type
        id: release-type
        run: |
          rel_type="release"
          case "${{ needs.get-tag.outputs.tag }}" in
            *alpha*) rel_type="alpha" ;;
            *beta*) rel_type="beta" ;;
            *) rel_type="release" ;;
          esac
          echo "::set-output name=type::$rel_type"

      - name: Upload to CurseForge
        uses: itsmeow/curseforge-upload@v3
        with:
          token: ${{ secrets.CF_API_TOKEN }}
          project_id: 123456
          game_endpoint: minecraft
          file_path: ${{ env.PROJECT_NAME }}-${{ needs.get-tag.outputs.tag }}.zip
          changelog: "${{ needs.changelog.outputs.changelog }}"
          changelog_type: markdown
          game_versions: java:Java 8,Forge,1.16.5
          release_type: ${{ steps.release-type.outputs.type }}
          # relations: mod:type

```

**Comment by froehlichA** [comment]
Nice! I'm definitely gonna take a modified version of the auto-release one, not so sure about the auto-upgrade one cuz modpacks generated that way aren't really guaranteed to work. But thanks for the files!

**Comment by MrAwesomeRocks** [comment]
That's why I made the auto-upgrade one create a PR. That way, you can test the modpack before releasing, and it should hopefully run often enough to only update one mod at a time.

**Comment by DAmNRelentless** [comment]
Since PAX is supposed to make the workflow easier when working with multiple people on the same project, I would prefer the GitFlow principle in that case.

**Comment by MrAwesomeRocks** [comment]
Did you read the [article](https://www.endoflineblog.com/oneflow-a-git-branching-model-and-workflow), specifically [this section](https://www.endoflineblog.com/oneflow-a-git-branching-model-and-workflow#variation-develop-master)? It's describing the problems with GitFlow **for working collaboratively** and proposes a solution.

**Comment by froehlichA** [comment]
My idea is to have the init command generate a ci script that runs when tags are added to commits, builds the mod pack, and uploads it to Curseforge. If you're savvy enough to change it to something that fits your workflow better, you can always go and do just that. But for the "common folk" that just want a working solution, this will suffice.

**Comment by MrAwesomeRocks** [comment]
Oh ok. I see your point. So you'll be primarily using the first script?

**Comment by froehlichA** [comment]
I haven't extensively looked at it yet, but yes, the final ci script will look similar.

**Comment by froehlichA** [comment]
Haven't tested it yet, but my version looks something like this:

<details>
  <summary>.github/workflows/main.yml</summary>

  ```yml
  name: main

  on:
    push:
      tags:
        - 'v*'

  env:
    PROJECT_ID: "123456"
  
  jobs:
    modpack-info:
      runs-on: ubuntu-latest
      outputs:
        version: ${{ steps.info.outputs.version }}
        loader: ${{ steps.info.outputs.loader }}
        projectname: ${{ steps.info.outputs.projectname }}
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Get modpack info
          id: info
          run: |
              manifestjson=`cat ./modpack/manifest.json`
              version=`echo $(jq -r '.minecraft.version' <<< "$manifestjson")`
              echo "::set-output name=version::$version"
              loader=`echo $(jq -r '.minecraft.modLoaders[0].id' <<< "$manifestjson")`
              loader=`echo ${loader%%-*}`
              loader="$(tr '[:lower:]' '[:upper:]' <<< ${loader:0:1})${loader:1}"
              echo "::set-output name=loader::$loader"
              projectname=`echo $(jq -r '.name' <<< "$manifestjson")`
              echo "::set-output name=projectname::$projectname"
  
    get-tag:
      runs-on: ubuntu-latest
      outputs:
        tag: ${{ steps.version.outputs.tag }}
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Get tag
          id: version
          uses: "WyriHaximus/github-action-get-previous-tag@v1"
  
    changelog:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Generate changelog
          id: changelog
          uses: metcalfc/changelog-generator@v1.0.0
          with:
            myToken: ${{ secrets.GITHUB_TOKEN }}
        - name: Write changelog to file
          run: echo '${{ steps.changelog.outputs.changelog }}' > changelog.txt
        - name: Store changelog
          uses: actions/upload-artifact@v2
          with:
            name: changelog
            path: CHANGELOG.md
  
    build:
      runs-on: ubuntu-latest
      needs: [changelog, get-tag, modpack-info]
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Download PAX
          uses: dsaltares/fetch-gh-release-asset@master
          with:
            repo: froehlichA/pax
            file: "pax"
            token: ${{ secrets.GITHUB_TOKEN }}
        - name: Download changelog
          uses: actions/download-artifact@v2
          with:
            name: changelog
        - name: Export modpack
          run: |
            sudo chmod +x ./pax
            ./pax export
        - name: Rename zip
          run: |
            mv .out/${{ needs.modpack-info.outputs.projectname }}.zip .out/${{ needs.modpack-info.outputs.projectname }}-${{ needs.get-tag.outputs.tag }}.zip
        - name: Upload zip
          uses: actions/upload-artifact@v2
          with:
            name: modpack
            path: .out/${{ needs.modpack-info.outputs.projectname }}-${{ needs.get-tag.outputs.tag }}.zip
    
    release-github:
      runs-on: ubuntu-latest
      needs: [build, changelog, get-tag, modpack-info]
      steps:
        - name: Download modpack
          uses: actions/download-artifact@v2
          with:
            name: modpack
        - name: Download changelog
          uses: actions/download-artifact@v2
          with:
            name: changelog
        - name: Create release
          uses: softprops/action-gh-release@v1
          with:
            body_path: CHANGELOG.md
            files: ${{ needs.modpack-info.outputs.projectname }}-${{ needs.get-tag.outputs.tag }}.zip
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
    release-curseforge:
      runs-on: ubuntu-latest
      needs: [build, changelog, get-tag, modpack-info]
      steps:
        - name: Download modpack
          uses: actions/download-artifact@v2
          with:
            name: modpack
        - name: Get release type
          id: release-type
          run: |
            rel_type="release"
            case "${{ needs.get-tag.outputs.tag }}" in
              *alpha*) rel_type="alpha" ;;
              *beta*) rel_type="beta" ;;
              *) rel_type="release" ;;
            esac
            echo "::set-output name=type::$rel_type"
        - name: Create release
          uses: itsmeow/curseforge-upload@v3
          with:
            token: ${{ secrets.CF_API_TOKEN }}
            project_id: ${{ env.PROJECT_ID }}
            game_endpoint: minecraft
            file_path: ${{ needs.modpack-info.outputs.projectname }}-${{ needs.get-tag.outputs.tag }}.zip
            changelog: "${{ needs.changelog.outputs.changelog }}"
            changelog_type: markdown
            game_versions: ${{ needs.modpack-info.outputs.loader }},${{ needs.modpack-info.outputs.version }}
            release_type: ${{ steps.release-type.outputs.type }}
  ```
</details>

- All commits tagged with `v*` will have the modpack built and uploaded to Github releases.
- To enable Curseforge releases, the user just has to specify the `env.PROJECT_ID` and `secrets.CF_API_TOKEN` variables.

**Comment by froehlichA** [comment]
Btw, added #29 for the `-y` parameter.

**Comment by MrAwesomeRocks** [comment]
Only change I'd recommend is to add `java:Java 8` to the `game_versions` field.

**Comment by MrAwesomeRocks** [comment]
Actually, I just noticed 2 things with your script @froehlichA :

1. The `modpack-info` and `get-tag` steps can probably be combined.
2. You need to specify an `outputs` section in the changelog step.

**Comment by froehlichA** [comment]
> The `modpack-info` and `get-tag steps` can probably be combined.

Probably, but they only take about 4 seconds each, so it's not a big deal.

> You need to specify an `outputs` section in the changelog step.

Yeah, thanks! :D I also noticed that when testing.

<details>
  <summary>updated ./.github/workflows/main.yml</summary>
  
  ```yaml
  name: main

  on:
    push:
      tags:
        - 'v*'
  
  env:
    PROJECT_ID: "495368"
  
  jobs:
    modpack-info:
      runs-on: ubuntu-latest
      outputs:
        version: ${{ steps.info.outputs.version }}
        loader: ${{ steps.info.outputs.loader }}
        projectname: ${{ steps.info.outputs.projectname }}
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Get modpack info
          id: info
          run: |
              manifestjson=`cat ./modpack/manifest.json`
              version=`echo $(jq -r '.minecraft.version' <<< "$manifestjson")`
              echo "::set-output name=version::$version"
              loader=`echo $(jq -r '.minecraft.modLoaders[0].id' <<< "$manifestjson")`
              loader=`echo ${loader%%-*}`
              loader="$(tr '[:lower:]' '[:upper:]' <<< ${loader:0:1})${loader:1}"
              echo "::set-output name=loader::$loader"
              projectname=`echo $(jq -r '.name' <<< "$manifestjson")`
              echo "::set-output name=projectname::$projectname"
  
    get-tag:
      runs-on: ubuntu-latest
      outputs:
        tag: ${{ steps.version.outputs.tag }}
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Get tag
          id: version
          uses: "WyriHaximus/github-action-get-previous-tag@v1"
  
    changelog:
      runs-on: ubuntu-latest
      outputs:
        changelog: ${{ steps.changelog.outputs.changelog }}
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Generate changelog
          id: changelog
          uses: heinrichreimer/github-changelog-generator-action@v2.1.1
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            output: CHANGELOG.md
            stripGeneratorNotice: true
        - name: Store changelog
          uses: actions/upload-artifact@v2
          with:
            name: changelog
            path: CHANGELOG.md
  
    build:
      runs-on: ubuntu-latest
      needs: [changelog, get-tag, modpack-info]
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Download PAX
          uses: dsaltares/fetch-gh-release-asset@master
          with:
            repo: froehlichA/pax
            file: "pax"
            token: ${{ secrets.GITHUB_TOKEN }}
        - name: Download changelog
          uses: actions/download-artifact@v2
          with:
            name: changelog
        - name: Export modpack
          run: |
            sudo chmod +x ./pax
            ./pax export
        - name: Rename zip
          run: |
            mv .out/${{ needs.modpack-info.outputs.projectname }}.zip .out/${{ needs.modpack-info.outputs.projectname }}-${{ needs.get-tag.outputs.tag }}.zip
        - name: Upload zip
          uses: actions/upload-artifact@v2
          with:
            name: modpack
            path: .out/${{ needs.modpack-info.outputs.projectname }}-${{ needs.get-tag.outputs.tag }}.zip
    
    release-github:
      runs-on: ubuntu-latest
      needs: [build, changelog, get-tag, modpack-info]
      steps:
        - name: Download modpack
          uses: actions/download-artifact@v2
          with:
            name: modpack
        - name: Download changelog
          uses: actions/download-artifact@v2
          with:
            name: changelog
        - name: Create release
          uses: softprops/action-gh-release@v1
          with:
            body_path: CHANGELOG.md
            files: ${{ needs.modpack-info.outputs.projectname }}-${{ needs.get-tag.outputs.tag }}.zip
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
    release-curseforge:
      runs-on: ubuntu-latest
      needs: [build, changelog, get-tag, modpack-info]
      steps:
        - name: Download modpack
          uses: actions/download-artifact@v2
          with:
            name: modpack
        - name: Get release type
          id: release-type
          run: |
            rel_type="release"
            case "${{ needs.get-tag.outputs.tag }}" in
              *alpha*) rel_type="alpha" ;;
              *beta*) rel_type="beta" ;;
              *) rel_type="release" ;;
            esac
            echo "::set-output name=type::$rel_type"
        - name: Create release
          uses: itsmeow/curseforge-upload@v3
          with:
            token: ${{ secrets.CF_API_TOKEN }}
            project_id: ${{ env.PROJECT_ID }}
            game_endpoint: minecraft
            file_path: ${{ needs.modpack-info.outputs.projectname }}-${{ needs.get-tag.outputs.tag }}.zip
            changelog: "${{ needs.changelog.outputs.changelog }}"
            changelog_type: markdown
            game_versions: ${{ needs.modpack-info.outputs.version }}
            release_type: ${{ steps.release-type.outputs.type }}
  ```
</details>

Apparently uploading files only works with the Minecraft version, curseforge surprisingly complains and returns `400` if you use `java: Java 8` or the mod loader (`Fabric` or `Forge`).

I've been testing this updated script for some time now, and everything seems to work.
